services:
  db: 
    image: mysql:latest
    container_name: mysql_mcapp
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      
    ports:
      - 3306:3306
    volumes:
      - type: bind
        source: ./database
        target: /docker-entrypoint-initdb.d/
      

  backend:
    build:
      context: ./backend
    container_name: backend_mcapp
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./backend:/app